language: c
compiler:
  - gcc
  - clang

before_install:
  - git clone https://github.com/bschwind/pigpio.git
  - cd pigpio
  - make
  - sudo make install
  - cd ..

script:
  - $CC transmit.c -lm -lpigpio -pthread -lrt
